sudo: required
dist: xenial
language: php
php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"
services:
  - mysql
before_install:
  - mysql -u root --password="" < tests/travis.sql
before_script:
  - sudo apt install composer
  - composer install
script:
  - php tests/test.php
