CREATE USER 'jahid'@'localhost' IDENTIFIED BY 'jahid';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP ON *.* TO 'jahid'@'localhost';
CREATE DATABASE IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
